<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SEDC.MovieApp.Domain\SEDC.MovieApp.Domain.csproj" />
    <ProjectReference Include="..\SEDC.MovieApp.Dtos\SEDC.MovieApp.Dtos.csproj" />
  </ItemGroup>

</Project>
